### ISSUE TITLE
Add Keynote speaker info

### ISSUE THREAD

**Issue by BigBlueHat** [RESTFest/2018.restfest.org#4]
Lorinda Brandon
Director, Developer Marketing
Capital One Platform Services

##### Your API’s Disappearing Act
APIs are often the gateways to get and post data, and delivering insights based on that data. Even if your API doesn’t deliver insights directly, chances are someone somewhere is using your API or related APIs to make sense of the world. But what does that world look like? Is it inclusive? Is it true? This talk will look at ways in which we not only marginalize/ostracize users but then build ongoing, ever-evolving insights based on completely inaccurate data. We’ll also examine ways in which your API or third-party APIs you consume may be contributing to this.

![Photo of Lorinda Brandon](https://user-images.githubusercontent.com/43209/41303609-ba4233be-6e3b-11e8-9a32-89b58b54c540.jpg)

**Comment by oestrich** [comment]
@BigBlueHat what should the snippet on the home page be? And the bio for Lorinda on the schedule page.

**Comment by BigBlueHat** [comment]
Good question! How's this?

"Chances are someone somewhere is using your API or related APIs to make sense of the world. But what does that world look like? Is it inclusive? Is it true? Lorinda Brandon of Capital One Platform Services will explore the insights and inaccuracies inherent in API design."

That look OK @lindybrandon?

@oestrich go ahead and post this when you have time--and we can manage feedback from Lindy if/wen it arrives.

Thanks!

**Comment by lindybrandon** [comment]
Looks good. :-)
Thank you

**Comment by oestrich** [comment]
Keynote info is up! 

http://2018.restfest.org/east/
http://2018.restfest.org/east/schedule#keynote

@lindybrandon what would you like your bio to be on the schedule page? That's the only thing I didn't have.

**Comment by lindybrandon** [comment]
Ah, here you go:

Lorinda Brandon has been living and breathing software for the last 35 years, with a particular focus on APIs in the last decade. She has held positions at companies like Kayak.com, Intuit, RR Donnelley, EMC, and now works at Capital One. Currently, one of her areas of focus is on the data behind APIs and what it means to provide and consume data in this increasingly digital world.
________________________________

**Comment by oestrich** [comment]
Everything should be up to date now!
